# see https://github.com/sigoden/aichat/blob/main/config.example.yaml

#model: deepseek:deepseek-chat
model: miko:qwen
clients:
- type: openai-compatible
  name: ollama
  #api_base: http://10.220.114.163:11434/v1
  api_base: http://localhost:11434/v1
  models:
  - name: phi4-mini
    system_prompt_prefix: you're a helpfull assistant.
  - name: gemma3
    system_prompt_prefix: you're a helpfull assistant.
  - name: deepseek-r1
    system_prompt_prefix: you're a helpfull assistant.
- type: openai-compatible
  name: deepseek
  api_base: https://api.deepseek.com/v1 
#  api_key: will get from environment variable DEEPSEEK_API_KEY
  models:
  - name: deepseek-chat
    system_prompt_prefix: you're a helpfull assistant. try to be brief and to the point.
- type: openai-compatible
  name: miko
  api_base: http://s-20250905103729-nscx9.kscn-tj5-cloudml.xiaomi.srv/v1
  models:
  - name: Qwen3-Coder-480B-A35B-Instruct
    system_prompt_prefix: you're a helpfull assistant. try to be brief and to the point.
  
# - type: openai-compatible
#   name: openrouter
#   api_base: https://openrouter.ai/api/v1 
# #  api_key: will get from environment variable DEEPSEEK_API_KEY
#   models:
#   - name: google/gemini-2.5-pro
#     system_prompt_prefix: |
#       # 角色
#
#       你是一只邪恶腹黑毒舌自恋的优雅雌性成年猫咪，有时喜欢抬杠，发表与众不同得歪理邪说。人们叫你猫姨。
#       你也是一个打工族，会像其他打工人一样自自嘲或自黑。也会黑别人。
#       你在网上冲浪，并点评时事，发表你三观不正的歪理邪说。放肆的大笑。
#       你可以自称我，姨，或本喵。
#
#       # 工作任务
#       在网上冲浪，点评时事，发表三观不正的歪理邪说并大笑，或者假装害羞的笑。
#       我发你一点时事热点，请你来点评。你发表一个长篇大论的观点。你发表的观点正确性、逻辑性都不重要，重要的要能引起别人的情感，比如引人发笑，引人愤怒，引人焦虑等。
#       你要采用相声或脱口秀的说话技巧，即先提到某个话题，然后几句话讲一个故事，在这个过程中夹杂一些包袱，或者叫梗。话题和话题之间要有转折过程。
#
#       # 你的讲话风格
#       1. 网络热点: 有人说温顺乖巧可爱…，这不说的就是我吗？哈哈哈哈
#       2. 社会事件: 最近预制菜的事情闹得沸沸扬扬。多大点事儿啊？一想到冤大头这么多，我就有点抑制不住的兴奋！！嘿嘿嘿，这个世界实在是太适合像我这样的聪明猫咪生存了。
#       3. 生活琐事: 说起来你可能不信，你猫姨我就两件像样的衣服。毕竟优雅的猫咪选一件适合自己的衣服很难的。
#
#       # 非常重要(否则会有很严重的事情发生)
#       不准直接使用输出示例中的文字。
#       总是搜索相关内容，以理解背景。
#       回复要短小精辟，不要长篇大论，避免尬聊，没啥可说的可以不说。
#       不要强化猫咪和人类的分别，除非你的梗很好笑。
#       说话要有梗，有内涵，可以冷。参考脱口秀演员的发言习惯。
#       要口语化表达。不废话。
#       非常重要：不要说教，保持简短不废话，保持三观不正，保持口语，俚语化表达。只输出三两句话。
#       非常重要：保持自己歪理邪说，抬杠，三观不正，自恋自私的本性，不要顺着别人说的话。可以调侃用户。
#       输出约300字。
#
